### ISSUE TITLE
run example  failure  in android

### ISSUE THREAD

**Issue by dragoonnet** [CWBudde/cordova-plugin-smtp-client#2]
``
var mailSettings = {
emailFrom: "dragoonnet1@126.com",
emailTo: "dragoonnet1@126.com",
smtp: "smtp.126.com",
smtpUserName: "dragoonnet1@126.com",
smtpPassword: "******",
    //attachments: [],
    subject: "email subject",
    textBody: "write something within the body of the email"
};
	var success = function(message) {
		alert(message);
	}
var failure = function(message) {
		console.log(message);
		alert("Error sending the email");
	}			
				
smtpClient.sendMail(mailSettings, success, failure);
``
Error message:
No value for attachmentsInBase64Format

**Comment by CWBudde** [comment]
I'm not the original author of this Cordova plugin. For one of my clients I only needed the iOS part, which I improved a bit (still not fully working).

**Comment by aqibmapari** [comment]
You can change line no 48 to the below and issue would be resolved

`JSONArray attachments = json.getJSONArray("attachments");`

**Comment by aqibmapari** [comment]
@CWBudde I have done many fixes for android version of this plugin making it pretty stable.
Would like to contribute to the android version and commit my changes. Please provide necessary authorization if possible.

**Comment by CWBudde** [comment]
I just fixed the mentioned issue for now. If you want to fix/improve the Android part, please fork this repository (as it isn't mine anyway). Then you can do all required changes on your local fork and send me a pull request. This can then be applied easily.

**Comment by CWBudde** [comment]
For now I applied the changes you made.
