### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by obeardwankenobi** [CWBudde/cordova-plugin-smtp-client#8]
Is it possible to turn off the notification advising an email has been sent?

**Comment by VisualMafia** [comment]
platforms/android/app/src/main/java/com/cordova/smtp/client/SMTPClient.java
remove string 35 to 48 "if (message.what == 0) {..."

**Comment by CWBudde** [comment]
It would be even better if this would be switchable somehow. Maybe someone can add an option for this, which can be set via JavaScript.
